/* =============================================================
   HISTÓRIA EM FOCO — Capítulos 1.43 a 1.57
   Parte V (América e o Sistema Colonial) e Parte VI (Brasil)
   ============================================================= */
window.ADICIONAR([

  /* ------------------------- PARTE V ------------------------- */
  { nome: "Parte V — América e o Sistema Colonial", capitulos: [

    { num: "1.43", titulo: "A Expansão Marítimo-Comercial e o Sistema Colonial", paragrafos: [
      "Nos séculos XV e XVI, Europa e América se encontraram pela primeira vez. As <abbr title=\"conjunto de viagens marítimas que ligaram a Europa ao restante do mundo\">Grandes Navegações</abbr> unificaram o planeta e deram origem ao <abbr title=\"conjunto de relações de exploração entre metrópole e colônia\">sistema colonial</abbr>: as potências europeias ocuparam terras estrangeiras, exploraram seus recursos e impuseram seu domínio.",
      "## Portugal e Espanha dividem o mundo",
      "Portugal buscava <abbr title=\"temperos como pimenta, cravo e canela\">especiarias</abbr> e metais preciosos. Em <abbr title=\"ano da chegada de Cabral ao Brasil\">1500</abbr>, <abbr title=\"o navegador que tomou posse do Brasil em nome de Portugal\">Pedro Álvares Cabral</abbr> chegou às terras que viriam a ser o Brasil. Para evitar conflitos, assinou-se o <abbr title=\"acordo de 1494 que dividiu as terras entre Portugal e Espanha\">Tratado de Tordesilhas</abbr>, que traçou uma linha imaginária no Atlântico: a leste dela ficaria para Portugal; a oeste, para a Espanha — um desenho que as outras potências logo contestariam.",
      "## A América Espanhola",
      "Os espanhóis conquistaram enormes impérios: <abbr title=\"o império asteca, no atual México\">os astecas</abbr> e <abbr title=\"o império inca, nos Andes\">os incas</abbr> foram dominados, respectivamente, por <abbr title=\"o conquistador espanhol do México\">Hernán Cortés</abbr> e <abbr title=\"o conquistador espanhol do Peru\">Francisco Pizarro</abbr>. Criaram o <abbr title=\"região colonial espanhola da América\">vice-reinados</abbr>, divididos em <abbr title=\"unidade territorial colonial espanhola\">províncias e audiências</abbr>, e montaram a <abbr title=\"instituição espanhola que fiscalizava a América\">Casa de Contratação de Sevilha</abbr>. Uma sociedade hierárquica formou-se: <abbr title=\"espanhóis nascidos na Europa\">chapetones</abbr>, <abbr title=\"filhos de espanhóis nascidos na América\">criollos</abbr>, <abbr title=\"descendentes de indígenas e espanhóis\">mestiços</abbr>, <abbr title=\"indígenas submetidos a trabalhos forçados\">indígenas</abbr> e <abbr title=\"africanos trazidos à força para o trabalho\">africanos escravizados</abbr>.",
      "## O mercantilismo",
      "O domínio colonial era guiado pelo <abbr title=\"política econômica que via riqueza no ouro e no comércio\">mercantilismo</abbr>: a colônia deveria <abbr title=\"produção dirigida ao comércio da metrópole\">exportar matérias-primas</abbr>, <abbr title=\"comércio restrito aos navios da metrópole\">comprar produtos da metrópole</abbr> e gerar <abbr title=\"diferença entre o que se vende e o que se compra\">saldo favorável</abbr>. Na prática, significava mais um <abbr title=\"esquema de domínio e extrativismo\">pilares de exploração</abbr> que transformaria a América em vasto celeiro para a Europa.",
      "## A colonização portuguesa",
      "No Brasil, a <abbr title=\"exploração inicial do pau-brasil pelos portugueses\">extração do pau-brasil (1500-1530)</abbr> cedeu lugar a uma colonização efetiva. D. João III dividiu a costa em <abbr title=\"terras doadas a nobres portugueses, de 1534 a 1536\">capitanias hereditárias</abbr> e os colonos implantaram engenhos e fortalezas. A partir do <abbr title=\"governo central que organizou a colônia a partir de 1549\">Governo-Geral (1549)</abbr>, a colonização ganhou forma: <abbr title=\"sistema de exploração colonial baseado na grande propriedade\">latifúndio</abbr>, <abbr title=\"monocultura voltada à exportação\">monocultura de exportação</abbr> e <abbr title=\"trabalho forçado de indígenas e africanos\">mão de obra escravizada</abbr> — o tripé que sustentaria o Brasil colonial."
    ], vocabulario: [
      ["sistema colonial", "relação de exploração entre metrópole e colônia"],
      ["mercantilismo", "política econômica que associava riqueza ao ouro e ao comércio"],
      ["criollos", "filhos de espanhóis nascidos na América"],
      ["capitanias hereditárias", "terras doadas por Portugal a nobres para colonizar"]
    ] },

    { num: "1.44", titulo: "A Montagem do Sistema Colonial: Economia Açucareira e Escravidão", paragrafos: [
      "A partir de meados do século XVI, o Brasil tornou-se o maior produtor mundial de <abbr title=\"produto que rendeu fortunas ao Brasil Colônia\">açúcar</abbr>. Em torno dos <abbr title=\"unidades de produção de açúcar do Brasil colonial\">engenhos</abbr>, organizou-se a sociedade colonial — rica, violenta e profundamente desigual.",
      "## A economia do açúcar",
      "O açúcar era produzido nas grandes <abbr title=\"vastas propriedades rurais de um único dono\">fazendas</abbr> do <abbr title=\"região litorânea do nordeste brasileiro\">Nordeste</abbr>. O <abbr title=\"donos dos engenhos, a elite colonial\">senhor de engenho</abbr> comandava a <abbr title=\"cultivo da cana em terra quase infinita\">lavoura de cana</abbr>, o <abbr title=\"máquina que moía a cana\">engenho</abbr> e as <abbr title=\"construções que ferviam o caldo para virar açúcar\">caldeiras e fornalhas</abbr>. O modelo era o mesmo da América inteira: <abbr title=\"a linha branca do latifúndio\">latifúndio</abbr>, <abbr title=\"cultivo de um só produto\">monocultura</abbr>, <abbr title=\"produção para o mercado externo\">exportação</abbr> e <abbr title=\"escravidão\">mão de obra escrava</abbr> — chamado de <abbr title=\"conjunto das relações do engenho colonial\">plantation</abbr>.",
      "## A escravidão",
      "A base do trabalho era a escravidão. Primeiro foram escravizados os <abbr title=\"povos indígenas escravizados no início da colonização\">indígenas</abbr>, capturados em expedições conhecidas como <abbr title=\"expedições que caçavam indígenas\">bandeiras de apresamento</abbr>. Depois, os portugueses passaram a importar <abbr title=\"pessoas traficadas da África para as Américas\">africanos escravizados</abbr>, trazidos no <abbr title=\"viagens que traziam africanos à força\">tráfico negreiro</abbr>. Calcula-se que o Brasil recebeu milhões de africanos — o maior destino de todo o tráfico. A escravidão marcou profundamente a <abbr title=\"sociedade formada pela população brasileira\">formação social e cultural do Brasil</abbr>.",
      "## A sociedade colonial",
      "A sociedade açucareira era dicotômica: de um lado, o <abbr title=\"os grandes proprietários rurais\">senhor</abbr>; do outro, <abbr title=\"os escravizados sem direitos\">os escravizados</abbr>. Entre eles, havia <abbr title=\"trabalhadores livres mas pobres\">agregados e lavradores</abbr>. Existiam também os <abbr title=\"sacerdotes que catequizavam índios e escravos\">jesuítas e missionários</abbr>, que protegiam os índios e educavam, e um pequeno grupo de <abbr title=\"comerciantes e funcionários da Coroa\">funcionários e comerciantes</abbr>. A vida era dura: <abbr title=\"falta de tudo que não era produzido na colônia\">escassez de alimentos</abbr>, doenças e castigos marcavam o cotidiano dos escravizados.",
      "## Resistência",
      "Os escravizados nunca se resignaram. <abbr title=\"fuga dos escravizados\">Fugiam</abbr>, formando <abbr title=\"comunidades de escravos fugidos\">quilombos</abbr> — o mais famoso, o <abbr title=\"quilombo formado na serra da Barriga, em Alagoas\">Quilombo dos Palmares</abbr>, durou quase um século e resistiu a dezenas de expedições militares. Também <abbr title=\"boicote ao trabalho e lentidão proposital\">boicotavam o trabalho</abbr> e preservavam <abbr title=\"religiões e culturas africanas\">religião, línguas e tradições</abbr>, que enriquecidas atravessaram séculos e chegaram às nossas ruas, mesas e altares."
    ], vocabulario: [
      ["engenho", "unidade de produção de açúcar da colônia"],
      ["plantation", "grande propriedade monocultora de exportação com escravos"],
      ["tráfico negreiro", "transporte forçado de africanos para as Américas"],
      ["quilombo", "comunidade formada por escravos fugidos"]
    ] },

    { num: "1.45", titulo: "A Administração Colonial: Capitanias e Governo-Geral", paragrafos: [
      "Portugal precisava administrar a vasta colônia. No início, tentou-se o modelo das <abbr title=\"terras doadas a nobres que deveriam colonizá-las\">capitanias hereditárias</abbr>, que falhou na maioria dos territórios. Em seguida, criou-se o <abbr title=\"governo central que unificou a administração colonial\">Governo-Geral</abbr> a fim de garantir a posse da terra.",
      "## As capitanias hereditárias",
      "Em 1534, o rei dividiu o litoral brasileiro em quinze <abbr title=\"lotes de terra doados aos capitães-donatários\">capitanias</abbr>, entregues a <abbr title=\"nobres que recebiam a terra para colonizar\">donatários</abbr>. Os donatários recebiam <abbr title=\"direito de administrar e lucrar com a capitania\">sesmarias, privilégios e poderes</abbr>, mas deviam investir por conta própria. Poucas prosperaram — <abbr title=\"a capitania de Pernambuco, que virou polo do açúcar\">Pernambuco</abbr> e <abbr title=\"a capitania de São Vicente, berço de São Paulo\">São Vicente</abbr> — e as demais foram <abbr title=\"capitanias que fracassaram por falta de recursos\">devastadas por ataques e falta de recursos</abbr>.",
      "## O Governo-Geral",
      "Em <abbr title=\"ano da criação do Governo-Geral\">1549</abbr>, <abbr title=\"o primeiro governador-geral do Brasil\">Tomé de Sousa</abbr> chegou em <abbr title=\"cidade fundada como sede do governo da colônia\">Salvador</abbr> com a missão de organizar a colônia. O governador-geral comandava vilas, justiça e defesa, auxiliado pelo <abbr title=\"funcionário que fiscalizava impostos\">provedor-mor da fazenda</abbr> e pelo <abbr title=\"funcionário que administrava a justiça\">ouvidor-mor</abbr>. Os <abbr title=\"sacerdotes jesuítas que catequizavam e criaram escolas\">jesuítas</abbr>, liderados por <abbr title=\"sacerdote que se tornou símbolo da catequese católica\">Manuel da Nóbrega</abbr>, fundaram <abbr title=\"escolas e missões que ensinavam os filhos dos índios e colonos\">colégios e missões</abbr>.",
      "## Câmaras e Cartas de Doação",
      "O poder local ficava nas mãos das <abbr title=\"conselhos municipais da colônia\">Câmaras Municipais</abbr>, formadas pelos <abbr title=\"os grandes proprietários locais\">homens-bons</abbr> — elite que controlava terras e escravos. As <abbr title=\"terras doadas por Portugal para incentivar o povoamento\">sesmarias</abbr> distribuíam terra fértil aos amigos do poder, enquanto as <abbr title=\"regularização das terras ocupadas\">cartas de sesmaria</abbr> legitimavam os domínios dos senhores. Dessa espinha vertebral — <abbr title=\"união de poder local e central\">capitanias, governos-gerais e câmaras</abbr> — nasceu a rede administrativa que controlava a colônia."
    ], vocabulario: [
      ["capitania hereditária", "lote de terra doado por Portugal a um donatário"],
      ["Governo-Geral", "governo central da colônia a partir de 1549"],
      ["Câmara Municipal", "conselho local formado pela elite colonial"],
      ["sesmaria", "doação de terras para incentivar o povoamento"]
    ] },

    { num: "1.46", titulo: "A Ocupação e a Expansão Territorial", paragrafos: [
      "O Tratado de Tordesilhas não durou muito: por guerras, comércio e o movimento dos <abbr title=\"expedições que desbravaram o interior do Brasil\">bandeirantes</abbr>, o território do Brasil cresceu muito além da linha imaginária, consolidando a forma que conhecemos hoje.",
      "## As invasões estrangeiras",
      "As riquezas do Brasil atraíram rivais. Os <abbr title=\"franceses que tentaram ocupar o litoral\">franceses</abbr> fundaram a <abbr title=\"colônia francesa no Maranhão\">França Antártica (Rio de Janeiro)</abbr> e a <abbr title=\"colônia francesa na atual Guiana\">França Equinocial (Maranhão)</abbr>, expulsas pelos portugueses. Os <abbr title=\"holandeses que invadiram o nordeste do Brasil\">holandeses</abbr> dominaram <abbr title=\"região nordestina dominada pelos holandeses de 1630 a 1654\">Pernambuco (1630-1654)</abbr> sob o governo de <abbr title=\"governador holandês que modernizou o Recife\">Maurício de Nassau</abbr>, estimulando a agricultura e as artes, até serem derrotados na <abbr title=\"batalhas que expulsaram os holandeses\">Insurreição Pernambucana de 1654</abbr>.",
      "## As bandeiras e o sertão",
      "Os <abbr title=\"expedições de São Paulo\">bandeirantes paulistas</abbr> adentraram o sertão atrás de <abbr title=\"indígenas que eram capturados para escravizar\">índios para escravizar</abbr>, <abbr title=\"ouro e pedras preciosas procuradas pelos bandeirantes\">ouro e pedras preciosas</abbr> e <abbr title=\"trabalhadores livres que vendiam produtos\">produtos do sertão</abbr>. Nomes como <abbr title=\"bandeirante que explorou o interior paulista\">Antônio Raposo Tavares</abbr> e <abbr title=\"bandeirante que explorou o norte e descobriu minas\">Fernão Dias Pais</abbr> alargaram as fronteiras a oeste do Tratado de Tordesilhas. Às expedições seguiram-se os <abbr title=\"criadores de gado que ocuparam o interior\">vaqueiros do gado</abbr>, os <abbr title=\"monges que evangelizavam os índios\">missionários</abbr> e os <abbr title=\"povoadores que fundaram vilas\">povoamentos</abbr>.",
      "## A expansão pela pecuária e pela fé",
      "A <abbr title=\"criação de gado que avançou pelos sertões\">pecuária</abbr> e as <abbr title=\"missões jesuíticas do sul\">missões jesuíticas</abbr> (sobretudo nos <abbr title=\"regiões de missões no interior sulino\">Sete Povos das Missões</abbr>) povoaram o Sul. Comércio e contrabando integraram a <abbr title=\"região amazônica\">Amazônia</abbr>, e a <abbr title=\"mineração que atraiu multidões a partir de 1690\">mineração de ouro e diamantes</abbr> em <abbr title=\"região das minas gerais\">Minas Gerais</abbr> acelerou o povoamento do interior. O <abbr title=\"tratado de 1750 que reconheceu as fronteiras atuais\">Tratado de Madri (1750)</abbr> consagrou o princípio do <abbr title=\"princípio que validava a posse pela ocupação\">uti possidetis</abbr>: quem ocupava, ficava. O mapa brasileiro, enfim, desenhou-se a cavalo, a passo de boi e a golpes de machado — muito além da linha de Tordesilhas."
    ], vocabulario: [
      ["bandeirantes", "expedições paulistas que desbravaram o interior"],
      ["pecuária", "criação de gado, que povoou os sertões"],
      ["Tratado de Madri", "tratado de 1750 que reconheceu as fronteiras do Brasil"],
      ["uti possidetis", "princípio de que quem ocupa a terra tem direito a ela"]
    ] },

    { num: "1.47", titulo: "A Crise do Sistema Colonial", paragrafos: [
      "No fim do século XVIII e início do XIX, o sistema colonial entrou em crise. O avanço das ideias <abbr title=\"movimento que pregava liberdade e igualdade\">iluministas</abbr>, as rebeliões na colônia e a política econômica de Portugal geraram tensões que explodiriam em <abbr title=\"movimentos de contestação no Brasil colonial\">conspirações e revoltas</abbr>.",
      "## As insatisfações na colônia",
      "Os colonos reclamavam dos <abbr title=\"impostos e tributos cobrados por Portugal\">altos impostos</abbr>, do <abbr title=\"comércio limitado aos portugueses\">monopólio comercial</abbr>, das <abbr title=\"punições a quem descumprisse as leis restritivas\">proibições de manufatura</abbr> e das <abbr title=\"práticas de repressão portuguesa\">represálias políticas</abbr>. As ideias <abbr title=\"pensadores de liberdade e razão da Europa do século XVIII\">iluministas</abbr> davam nova linguagem às queixas: o direito natural de <abbr title=\"liberdade individual e propriedade\">liberdade e igualdade</abbr> e a <abbr title=\"ideia de que o povo pode escolher seus governantes\">soberania popular</abbr>.",
      "## A Inconfidência Mineira",
      "Em <abbr title=\"ano da conjuração mineira\">1789</abbr>, um grupo de <abbr title=\"os ricos mineiros contrários aos impostos\">elites de Vila Rica</abbr> planejou a <abbr title=\"rebelião que pretendia separar Minas de Portugal\">Inconfidência Mineira</abbr>. Inspirados na independência <abbr title=\"independência dos Estados Unidos de 1776\">norte-americana</abbr> e nas <abbr title=\"ideias iluministas\">ideias francesas</abbr>, sonhavam instalar uma república em Minas. O movimento foi <abbr title=\"a conspiração descoberta e denunciada\">delatado antes de acontecer</abbr>, e o líder <abbr title=\"o alferes condenado à forca, símbolo da revolta\">Tiradentes</abbr> foi enforcado. Apesar da derrota, a Inconfidência fixou imagens de heroísmo na memória nacional.",
      "## A Conjuração Baiana",
      "Em <abbr title=\"ano da revolta baiana\">1798</abbr>, <abbr title=\"movimento popular baiano de ideias revolucionárias\">a Conjuração Baiana</abbr> seguiu caminho mais radical: povos pobres, escravos e libertos lutaram por <abbr title=\"extinção da escravidão e igualdade\">abolição, república e igualdade social</abbr>. Reprimida com violência, mostrou que havia uma <abbr title=\"combustão social que escravos e pobres representavam\">fagulha revolucionária nas camadas mais baixas</abbr>.",
      "## O encerramento da era colonial",
      "A crise completou-se quando <abbr title=\"transferência da corte portuguesa para o Brasil em 1808\">a família real desembarcou no Rio em 1808</abbr>, fugindo das tropas de <abbr title=\"imperador francês que invadiu Portugal\">Napoleão</abbr>. A abertura dos portos e a elevação do Brasil a reino mostraram que a colônia, na prática, havia acabado. A <abbr title=\"revolução do Porto de 1820 que exigiu o retorno de D. João\">Revolução do Porto</abbr>, que exigiu a volta do rei, puxaria o gatilho definitivo: a <abbr title=\"processo que culminou na independência de 1822\">independência do Brasil</abbr>."
    ], vocabulario: [
      ["iluminismo", "movimento que pregou razão, liberdade e igualdade"],
      ["Inconfidência Mineira", "conspiração de 1789 contra os impostos"],
      ["Conjuração Baiana", "revolta popular de 1798 na Bahia"],
      ["soberania popular", "poder de decisão que pertence ao povo"]
    ] }
  ]},

  /* ------------------------- PARTE VI ------------------------- */
  { nome: "Parte VI — Brasil: da Colônia à República Populista", capitulos: [

    { num: "1.48", titulo: "A Vinda da Corte e o Período Joanino", paragrafos: [
      "Em 1807, as tropas de <abbr title=\"imperador francês que invadiu Portugal\">Napoleão Bonaparte</abbr> marcharam sobre Portugal. Para não perder o império, o príncipe regente <abbr title=\"príncipe de Portugal que veio ao Brasil\">D. João</abbr> embarcou com a <abbr title=\"família real portuguesa\">família real</abbr> e aproximadamente dez mil pessoas para o Brasil. Em <abbr title=\"data histórica da chegada da corte ao Rio de Janeiro\">março de 1808</abbr>, chegavam ao Rio de Janeiro, mudando para sempre a colônia.",
      "## As transformações de 1808",
      "Mal desembarcou, D. João decretou a <abbr title=\"fim do monopólio comercial aliado à Inglaterra\">Abertura dos Portos às nações amigas</abbr>, quebrando o <abbr title=\"política que restringia o comércio\">exclusivo metropolitano</abbr>. Depois, criou órgãos que a colônia nunca tivera: o <abbr title=\"banco fundado em 1808\">Banco do Brasil</abbr>, a <abbr title=\"biblioteca real que veio de Portugal\">Biblioteca Nacional</abbr>, a <abbr title=\"escola de medicina\">Escola de Cirurgia</abbr>, a <abbr title=\"jornal da corte\">Gazeta do Rio de Janeiro</abbr> e as <abbr title=\"academias militar e naval\">academias militares</abbr>. Com eles, o Rio virou a capital do império português.",
      "## A vida na corte",
      "A cidade se transformou: <abbr title=\"urbanização do Rio de Janeiro\">alargaram-se ruas\</abbr>, construíram-se <abbr title=\"palácio de São Cristóvão, sede da corte\">palácios\</abbr> e <abbr title=\"melhoramentos urbanos\">incentivo às praças e quarteirões\</abbr>. Em 1810, Portugal assinou com a Inglaterra <abbr title=\"tratados de amizade e comércio com a Inglaterra\">tratados vantajosos</abbr>, e os ingleses dominaram o comércio brasileiro. Em <abbr title=\"ano em que o Brasil foi elevado a reino unido a Portugal\">1815</abbr>, o Brasil foi elevado a <abbr title=\"condição de Reino Unido de Portugal, Brasil e Algarves\">Reino Unido</abbr>, deixando de ser oficialmente colônia.",
      "## A Revolução do Porto e a volta",
      "Em <abbr title=\"ano da revolução liberal portuguesa\">1820</abbr>, estourou em Portugal a <abbr title=\"movimento liberal português que exigia a volta do rei\">Revolução do Porto</abbr>: os portugueses queriam o rei de volta e a <abbr title=\"espécie de constituição que limitava o poder real\">Constituição</abbr>, e temiam a <abbr title=\"perda do monopólio sobre o Brasil\">independência econômica do Brasil</abbr>. D. João VI retornou a Portugal em <abbr title=\"ano da volta de D. João a Portugal\">1821</abbr>, deixando seu filho <abbr title=\"herdeiro do trono que ficou no Brasil\">D. Pedro</abbr> como príncipe regente — e o conselho \"<abbr title=\"instrução dada a D. Pedro para evitar a independência\">aconselhemo-vos a subir ao trono antes que algum aventureiro o faça\</abbr>\". Seria a senha para o grito de independência."
    ], vocabulario: [
      ["Abertura dos Portos", "liberação do comércio brasileiro em 1808"],
      ["Reino Unido", "elevação do Brasil a reino duplo em 1815"],
      ["Revolução do Porto", "movimento liberal português de 1820"],
      ["corte", "conjunto da família real e dos órgãos do governo"]
    ] },

    { num: "1.49", titulo: "O Processo de Independência", paragrafos: [
      "A independência do Brasil, em <abbr title=\"data de 7 de setembro de 1822\">7 de setembro de 1822</abbr>, não foi um grito isolado: foi o desfecho de um processo turbulento que envolveu as cortes portuguesas, a elite brasileira e o príncipe D. Pedro.",
      "## As pressões que empurraram a separação",
      "As cortes portuguesas tentaram <abbr title=\"intenção de recolarionizar o Brasil\">recolonizar o Brasil</abbr>: exigiram <abbr title=\"retorno forçado de D. Pedro\">a volta de D. Pedro\</abbr>, <abbr title=\"suspensão dos órgãos criados no Brasil\">extinguir o Banco do Brasil\</abbr> e <abbr title=\"voltar a restringir o comércio\">restringir o comércio\</abbr>. A elite brasileira, que vivera os anos da corte e não queria perder o que conseguira, pressionou D. Pedro a permanecer. O príncipe respondeu: \"<abbr title=\"frase de D. Pedro recusando obedecer às cortes\">Se é para o bem de todos e felicidade geral da nação, digam ao povo que fico</abbr>\" — o <abbr title=\"dia de D. Pedro, 9 de janeiro de 1822\">Fico</abbr>.",
      "## O caminho até o grito",
      "Em <abbr title=\"ano em que D. Pedro rompeu com as cortes\">1822</abbr>, D. Pedro <abbr title=\"recusa às ordens de Lisboa\">desobedeceu às cortes</abbr>, convocou uma <abbr title=\"assembleia para organizar o novo país\">Assembleia Constituinte</abbr> e se tornou <abbr title=\"título dado a D. Pedro no Brasil\">Defensor Perpétuo do Brasil</abbr>. Em viagem a São Paulo, recebeu as últimas ordens de Lisboa. Às margens do <abbr title=\"riacho onde ocorreu o grito de independência\">rio Ipiranga</abbr>, em 7 de setembro, ergueu o grito — segundo a tradição — \"<abbr title=\"a frase histórica da independência\">Independência ou Morte!</abbr>\". Em <abbr title=\"data da aclamação de D. Pedro como imperador\">12 de outubro</abbr>, foi aclamado <abbr title=\"título de D. Pedro I nas cerimônias\">Imperador do Brasil\</abbr>.",
      "## O reconhecimento internacional",
      "A independência precisou de reconhecimento. A <abbr title=\"países que só reconheceram em troca de privilégios comerciais\">Inglaterra reconheceu o novo país</abbr> em troca da manutenção do tráfico negreiro e de vantagens comerciais; os <abbr title=\"os Estados Unidos reconheceram a independência em 1824\">Estados Unidos</abbr>, em 1824; e <abbr title=\"Portugal, que reconheceu com indenização\">Portugal</abbr> reconheceu mediante pagamento. Em <abbr title=\"tratado que selou o reconhecimento de Portugal\">1825</abbr>, Portugal aceitou o fato consumado.",
      "## Uma independência conservadora",
      "A independência brasileira foi <abbr title=\"processo liderado pela elite e pela monarquia\">conduzida pela elite agrária e pela monarquia</abbr>, sem participação popular: o povo assistiu de longe, muitos escravos não souberam, e ninguém foi libertado. Diferente das repúblicas vizinhas, manteve-se a <abbr title=\"governo de um imperador\">monarquia</abbr>, a <abbr title=\"manutenção da escravidão\">escravidão</abbr> e a <abbr title=\"grandes propriedades rurais\">estrutura agrária\</abbr>. O Brasil trocava de metrópole, mantendo os mesmos donos do poder."
    ], vocabulario: [
      ["Dia do Fico", "decisão de D. Pedro de permanecer no Brasil em 1822"],
      ["recolonização", "tentativa das cortes de reimpor o domínio de Portugal"],
      ["independência conservadora", "separação feita pela elite, sem mudanças sociais"],
      ["Defensor Perpétuo", "título dado a D. Pedro nas vésperas da independência"]
    ] },

    { num: "1.50", titulo: "O Primeiro Reinado", paragrafos: [
      "De <abbr title=\"período de 1822 a 1831\">1822 a 1831</abbr>, o Brasil foi governado pelo imperador <abbr title=\"imperador do Brasil no Primeiro Reinado\">D. Pedro I</abbr>. Foi um reinado de autoritarismo, guerras, reações e desgastes que terminou com a abdicação do imperador.",
      "## A Constituição de 1824",
      "A <abbr title=\"assembleia que escreveria a primeira constituição\">Assembleia Constituinte de 1823</abbr> foi <abbr title=\"dissolução da assembleia pelo imperador\">dissolvida por D. Pedro I</abbr> — episódio conhecido como <abbr title=\"a noite em que o exército cercou a constituinte\">a Noite da Agonia</abbr>. O imperador impôs então a <abbr title=\"constituição outorgada em 1824\">Carta de 1824</abbr>, que criava o <abbr title=\"poder do imperador acima dos outros três\">Poder Moderador</abbr>, centralizava o Estado e mantinha o <abbr title=\"monopólio do imperador na escolha do governo\">monopólio do poder</abbr>. Para acalmar as províncias, a constituição dividia o país em <abbr title=\"divisão administrativa levando a chamada província\">províncias</abbr> governadas por <abbr title=\"governadores escolhidos pelo imperador\">presidentes nomeados</abbr>.",
      "## Guerras e revoltas",
      "O 1º Reinado enfrentou guerras e rebeliões: a <abbr title=\"guerra contra as províncias da Cisplatina (1825-1828)\">Guerra da Cisplatina</abbr> contra a <abbr title=\"província que se tornaria o Uruguai\">província da Cisplatina</abbr>; a <abbr title=\"confederação do Equador, revolta em Pernambuco em 1824\">Confederação do Equador</abbr>, reprimida com violência; e a <abbr title=\"motins militares e provinciais do fim do período\">agitação militar e política crescente</abbr>.",
      "## O dinheiro e o povo",
      "A economia foi marcada pela <abbr title=\"crise da dívida externa após a independência\">dívida externa</abbr>, pelo <abbr title=\"negociação do reconhecimento com a Inglaterra\">favorecimento inglês</abbr> e pelo <abbr title=\"manutenção do comércio de escravos\">tráfico de escravos</abbr>, que as pressões inglesas tentavam abolir. Os jornais <abbr title=\"imprensa que criticava o imperador\">de oposição</abbr> cresciam, e os <abbr title=\"membros radicais que defendiam a república\">liberais exaltados</abbr> atacavam o poder pessoal do rei.",
      "## A abdicação",
      "O desgaste chegou ao limite quando D. Pedro I <abbr title=\"recusa de D. Pedro em apoiar a sucessão de seu irmão em Portugal\">se envolveu numa grave questão em Portugal</abbr> (a sucessão de seu irmão D. Miguel), empregando recursos e atenção brasileiros. A <abbr title=\"noite de 7 de abril de 1831\">Noite das Garrafadas</abbr> e as <abbr title=\"greve e motim rural chamado Sete de Abril\">agitações de 1831</abbr> selaram o destino. Em <abbr title=\"data da abdicação de D. Pedro I\">7 de abril de 1831</abbr>, D. Pedro I abdicou em favor de seu filho de cinco anos, <abbr title=\"o futuro imperador D. Pedro II\">D. Pedro de Alcântara</abbr>, e partiu para Portugal. O Brasil entrava no <abbr title=\"período em que o país foi governado por regentes\">Período Regencial</abbr>."
    ], vocabulario: [
      ["Poder Moderador", "poder imperial acima dos outros três poderes"],
      ["abdicação", "renúncia do trono por D. Pedro I"],
      ["Noite da Agonia", "dissolução da Constituinte de 1823"],
      ["Cisplatina", "província que se tornaria o Uruguai"]
    ] },

    { num: "1.51", titulo: "O Período Regencial", paragrafos: [
      "De <abbr title=\"período de 1831 a 1840\">1831 a 1840</abbr>, com o imperador criança, o Brasil foi governado por <abbr title=\"governantes temporários na menoridade de D. Pedro II\">regentes</abbr>. Foi uma década de experimentos políticos e de muitas revoltas provinciais.",
      "## Os regentes e as reformas",
      "Os governos regenciais buscaram descentralizar o poder e acalmar o país. A <abbr title=\"lei que retirou poderes da polícia do imperador\">reforma do Código de Processo</abbr> e o <abbr title=\"lei que transformou as províncias em unidades com assembleias\">Ato Adicional de 1834</abbr> criaram <abbr title=\"assembleias legislativas provinciais\">assembleias provinciais</abbr> e a <abbr title=\"regência una da capital\">Regência Una</abbr>. O padre <abbr title=\"regente conservador conhecido pelo Código de Processo\">Diogo Feijó</abbr> liderou a regência mais liberal; <abbr title=\"regentes conservadores que assumiram depois\">Araújo Lima e a Regência Una conservadora</abbr> sucederam-no.",
      "## As revoltas provinciais",
      "As províncias explodiram em revoltas: a <abbr title=\"revolta paraense de 1835 a 1840\">Cabanagem, no Pará</abbr>, que enfrentou a elite; a <abbr title=\"revolta gaúcha da Guerra dos Farrapos, de 1835 a 1845\">Revolução Farroupilha</abbr>, que proclamou a <abbr title=\"república gaúcha separatista\">República Rio-Grandense</abbr>; a <abbr title=\"revolta baiana escrava de 1835\">Revolta dos Malês</abbr>, planejada por escravos muçulmanos; a <abbr title=\"revolta popular de 1837 na Bahia\">Sabinada, na Bahia</abbr>; e a <abbr title=\"revolta maranhense de 1838 a 1841\">Balaiada, no Maranhão</abbr>. De repente, o Brasil parecia um mosaico de repúblicas em chamas.",
      "## A centralização conservadora",
      "A onda de revoltas convenceu os conservadores e parte dos liberais de que era preciso <abbr title=\"fortalecimento do poder central\">centralizar novamente o poder</abbr>. Nasceu a <abbr title=\"grupo político que pregava ordem e centralização\">política de maior rigor</abbr>, resumida por <abbr title=\"jornalista e ideólogo da centralização\">Bernardo Pereira de Vasconcelos</abbr>: \"Fiz como o <abbr title=\"viajante que volta atrás para consertar o caminho\">viajante que erra o caminho\</abbr>\". O <abbr title=\"golpe que antecipou a maioridade\">Golpe da Maioridade (1840)</abbr> acelerou a coroação de <abbr title=\"imperador aclamado aos 14 anos\">D. Pedro II</abbr>, que assumiu o trono antes dos 15 anos.",
      "## O balanço do período",
      "O Período Regencial foi um laboratório político: nele se testaram <abbr title=\"conselhos de regência e reformas\">modelos de governo</abbr>, organizaram-se os <abbr title=\"partidos políticos do império\">partidos Liberal e Conservador</abbr> e afloraram as desigualdades regionais e sociais. A quem observa de longe, parece o preço pesado que a unidade nacional cobrou — mas foi também a escola onde o Brasil aprendeu a administrar a sua enorme diversidade."
    ], vocabulario: [
      ["regência", "governo provisório na menoridade do imperador"],
      ["Ato Adicional de 1834", "lei que criou assembleias provinciais"],
      ["Cabanagem", "revolta paraense de 1835 a 1840"],
      ["Golpe da Maioridade", "antecipação da coroação de D. Pedro II em 1840"]
    ] },

    { num: "1.52", titulo: "O Segundo Reinado", paragrafos: [
      "O <abbr title=\"período de 1840 a 1889 em que o Brasil foi governado por D. Pedro II\">Segundo Reinado</abbr> foi a fase mais longa e estável da monarquia brasileira. Quase cinquenta anos de ouro do café e tensões crescentes, que terminariam com a proclamação da república.",
      "## O café e a economia",
      "O <abbr title=\"produto que moveu a economia do século XIX\">café</abbr> espalhou-se pelo <abbr title=\"região do vale do Paraíba, entre Rio e São Paulo\">Vale do Paraíba</abbr> e depois pelo <abbr title=\"oeste paulista\">Oeste Paulista</abbr>. Os <abbr title=\"donos das fazendas de café\">fazendeiros</abbr>, chamados <abbr title=\"homens ricos do café\">barões do café</abbr>, enriqueceram e mandavam na política. As estradas de <abbr title=\"estradas de ferro que escoavam o café\">ferro</abbr> ligaram o interior aos portos, e a <abbr title=\"indústria que começava a surgir\">industrialização inicial</abbr> ganhou força com <abbr title=\"empresário da indústria nacional\">Irineu Evangelista de Souza, o Barão de Mauá</abbr>.",
      "## A política e a guerra",
      "O imperador <abbr title=\"imperador que governou com o parlamentarismo às avessas\">D. Pedro II</abbr> alternava os <abbr title=\"os partidos do império\">partidos Liberal e Conservador</abbr> no poder, num <abbr title=\"sistema em que o imperador escolhia o gabinete\">parlamentarismo às avessas</abbr>. O Brasil travou a <abbr title=\"a maior guerra sul-americana, de 1864 a 1870\">Guerra do Paraguai</abbr> contra <abbr title=\"o ditador paraguaio Solano López\">Solano López</abbr>, vencida a duras penas pelos <abbr title=\"aliança de Brasil, Argentina e Uruguai\">Aliados</abbr>. A guerra inflou o Exército e criou heróis — mas também custou vidas e amargo para o tesouro.",
      "## O movimento abolicionista",
      "A <abbr title=\"pressão inglesa e o movimento interno\">luta contra a escravidão</abbr> avançou devagar: a <abbr title=\"lei de 1850 que proibiu o tráfico negreiro\">Lei Eusébio de Queirós</abbr>, a <abbr title=\"lei de 1871 que libertava crianças nascidas de escravas\">Lei do Ventre Livre</abbr> e a <abbr title=\"lei de 1885 que libertava escravos acima de 60 anos\">Lei dos Sexagenários</abbr>. Em <abbr title=\"a maior abolição do mundo, sem indenização\">13 de maio de 1888</abbr>, a <abbr title=\"lei que aboliu a escravidão no Brasil\">Lei Áurea</abbr> foi assinada pela princesa <abbr title=\"princesa que assinou a Lei Áurea\">Isabel</abbr>. Dezenas de milhares de pessoas foram libertadas, mas os <abbr title=\"ex-escravizados que não receberam terras nem salários\">libertos</abbr> ficaram sem apoio, e a desigualdade continuou.",
      "## A queda da monarquia",
      "A monarquia acumulou inimigos: os <abbr title=\"igreja que brigou com o imperador na questão religiosa\">militares, influenciados pelo positivismo</abbr>, os <abbr title=\"fazendeiros de café insatisfeitos\">fazendeiros</abbr> e os <abbr title=\"clero católico\">setores urbanos</abbr>. Em <abbr title=\"data da proclamação da república\">15 de novembro de 1889</abbr>, o <abbr title=\"golpe militar do marechal Deodoro\">marechal Deodoro da Fonseca</abbr> proclamou a república. <abbr title=\"família imperial exilada após a proclamação\">D. Pedro II foi exilado</abbr>, e o Brasil trocou o trono imperial por um novo regime republicano que, na prática, seguia sob o comando das elites."
    ], vocabulario: [
      ["Segundo Reinado", "período do governo de D. Pedro II, de 1840 a 1889"],
      ["Lei Áurea", "lei de 1888 que aboliu a escravidão"],
      ["Guerra do Paraguai", "guerra de 1864 a 1870 na América do Sul"],
      ["parlamentarismo às avessas", "sistema em que o imperador controlava o gabinete"]
    ] },

    { num: "1.53", titulo: "O Advento da República", paragrafos: [
      "A <abbr title=\"proclamação da república em 1889\">República</abbr> nasceu de um golpe, mas representou também o desgaste do império. Nos primeiros anos, o novo regime foi dominado pelos militares e, em seguida, pelos barões do café.",
      "## Os primeiros governos",
      "O <abbr title=\"primeiro presidente do Brasil\">marechal Deodoro da Fonseca</abbr> governou de forma autoritária e fechou o <abbr title=\"congresso nacional recém-criado\">Congresso</abbr>, o que o levou a renunciar. Seu sucessor, <abbr title=\"segundo presidente do Brasil\">Floriano Peixoto</abbr>, o \"<abbr title=\"apelido de Floriano\">Marechal de Ferro</abbr>\", reprimiu revoltas como a <abbr title=\"revolta da Armada, na Marinha\">Revolta da Armada</abbr> e a <abbr title=\"revolução federalista do sul\">Revolução Federalista</abbr>.",
      "## A Revolta da Armada e Canudos",
      "Deodoro mandou bombardear o Rio e Floriano enfrentou a <abbr title=\"insurreição naval de 1893\">Revolta da Armada</abbr>. No sertão baiano, o líder <abbr title=\"líder religioso de Canudos\">Antônio Conselheiro</abbr> reuniu milhares de seguidores no <abbr title=\"comunidade religiosa do sertão baiano\">arraial de Canudos</abbr>, visto como ameaça pela república. As <abbr title=\"expedições militares contra Canudos\">campanhas militares</abbr>, retratadas por Euclides da Cunha em <abbr title=\"o livro que narrou a guerra de Canudos\">Os Sertões</abbr>, destruíram a comunidade em <abbr title=\"destruição final de Canudos em outubro de 1897\">1897</abbr>.",
      "## A Constituição de 1891",
      "A <abbr title=\"primeira constituição republicana\">Constituição de 1891</abbr> adotou o <abbr title=\"sistema de governo em que o presidente é eleito\">presidencialismo</abbr>, o <abbr title=\"federação de estados com autonomia\">federalismo</abbr> e o <abbr title=\"separação entre Estado e Igreja\">laicismo</abbr>. O voto, no entanto, era <abbr title=\"voto aberto e público\">aberto</abbr> e <abbr title=\"restrito à maioria que sabia ler\">excluía analfabetos e mulheres</abbr> — na prática, as elites continuavam no comando. Os <abbr title=\"estados do norte e do sul com poderes regionais\">estados</abbr> ganharam bandeiras próprias, enquanto o <abbr title=\"cidade capital federal\">Distrito Federal (Rio de Janeiro)</abbr> abrigava o governo.",
      "## A república das oligarquias",
      "A partir de <abbr title=\"ano em que a elite civil assumiu a república\">1894</abbr>, com <abbr title=\"primeiro presidente civil, paulista\">Prudente de Morais</abbr>, o poder passou às <abbr title=\"domínio político dos grandes estados\">oligarquias estaduais</abbr>. Formou-se a chamada <abbr title=\"aliança entre café com leite (SP e MG)\">política do café com leite</abbr>, alternando presidentes <abbr title=\"presidentes vindos de São Paulo\">paulistas</abbr> e <abbr title=\"presidentes vindos de Minas Gerais\">mineiros</abbr> no poder. A república dos barões se instalava — e com ela, a necessidade de reformas que viriam nas décadas seguintes."
    ], vocabulario: [
      ["proclamação da república", "golpe militar de 15 de novembro de 1889"],
      ["Constituição de 1891", "primeira constituição republicana do Brasil"],
      ["oligarquia", "governo dominado por um pequeno grupo"],
      ["política do café com leite", "aliança entre São Paulo e Minas Gerais"]
    ] },

    { num: "1.54", titulo: "A República Velha: Política e Economia", paragrafos: [
      "A <abbr title=\"período da república de 1889 a 1930, chamada Primeira República\">República Velha</abbr> foi dominada pelas elites agrárias e marcada por fraudes, coronéis e exclusão social. Ao mesmo tempo, o Brasil cresceu — com o café, a borracha e o início da indústria.",
      "## O poder dos coronéis",
      "Nas áreas rurais, o <abbr title=\"chefe político local no interior, o coronel\">coronel</abbr> controlava votos com <abbr title=\"práticas de controle do voto do coronelismo\">favores, ameaças e violência</abbr> — o <abbr title=\"sistema de troca de favores políticos\">coronelismo</abbr>. O voto era <abbr title=\"votação em que o chefe via o voto de cada um\">aberto e vigiado</abbr>, e as eleições eram rotineiramente <abbr title=\"fraudes eleitorais da república velha\">fraudadas</abbr>. Esse esquema ficou conhecido como <abbr title=\"política de favorecer políticos aliados de cada estado\">política dos governadores</abbr>, com a troca de favores entre o governo central e os estados.",
      "## A economia do café",
      "O <abbr title=\"produto que sustentou a economia da Primeira República\">café</abbr> era o motor do país. Para segurar os preços, o governo acionou o <abbr title=\"compra de café excedente pelo governo\">Convênio de Taubaté (1906)</abbr> — a estocagem comprada pelo Estado — e criou políticas de <abbr title=\"política de valorização do café\">valorização do produto</abbr>. A <abbr title=\"região amazônica, com o ciclo da borracha\">borracha</abbr> enriqueceu a Amazônia até o contrabando de sementes para a Ásia quebrar o mercado. A <abbr title=\"primeiras indústrias de tecido e alimentos\">indústria</abbr> deu os primeiros passos com imigrantes e <abbr title=\"empresários como Irineu de Mauá\">capitais do café</abbr>.",
      "## Migrações e cidades",
      "Milhões de <abbr title=\"imigrantes europeus e asiáticos que vieram ao Brasil\">imigrantes</abbr> — italianos, portugueses, espanhóis, japoneses — povoaram as fazendas e as cidades. As <abbr title=\"cidades que cresceram com a industrialização\">cidades</abbr> se modernizaram: <abbr title=\"reforma urbana do Rio de Janeiro, com o bota-abaixo\">o Rio reformou-se\</abbr> sob <abbr title=\"prefeito do Rio que liderou a reforma urbana\">Pereira Passos</abbr>, e a <abbr title=\"doença da febre amarela\">saúde pública</abbr> avançou com <abbr title=\"médico sanitarista que combateu epidemias\">Oswaldo Cruz</abbr>. Surgiu o <abbr title=\"movimento operário das cidades\">movimento operário</abbr>, com <abbr title=\"sindicalismo trazido pelos anarquistas\">anarquistas</abbr> e <abbr title=\"partido comunista brasileiro fundado em 1922\">comunistas</abbr> disputando os trabalhadores.",
      "## As tensões e o caminho da mudança",
      "A riqueza do café escondia <abbr title=\"fraudes e concentração de renda\">mazelas profundas</abbr>. <abbr title=\"revoltas urbanas de 1904\">a Revolta da Vacina</abbr>, <abbr title=\"grevismo do início do século\">as grandes greves de 1917</abbr>, o <abbr title=\"movimento de jovens oficiais dos anos 1920\">tenentismo</abbr> e a <abbr title=\"semana de arte moderna de 1922\">Semana de Arte Moderna</abbr> mostravam o descontentamento. O acordo do café com leite, frágil, esgotava-se: as novas forças exigiam participação, e a república velha caminhava para seu fim."
    ], vocabulario: [
      ["coronel", "chefe político rural que controlava os votos"],
      ["coronelismo", "sistema de favores e controle político no interior"],
      ["Convênio de Taubaté", "política de compra de café excedente em 1906"],
      ["tenentismo", "movimento de jovens militares nos anos 1920"]
    ] },

    { num: "1.55", titulo: "A República Velha: Crise e Revolução de 1930", paragrafos: [
      "Na década de 1920, a República Velha começou a rachar: os militares contestaram o governo, a economia desigual gerou insatisfação, e a quebra da bolsa de Nova York em 1929 derramou o café e o regime. Em <abbr title=\"revolução que terminou a Primeira República em 1930\">1930</abbr>, a aliança liderada por Getúlio Vargas chegou ao poder.",
      "## O tenentismo",
      "Os <abbr title=\"jovens oficiais do exército\">tenentes</abbr>, descontentes com as fraudes eleitorais e o poder das oligarquias, lideraram revoltas como a <abbr title=\"revolta do forte de Copacabana em 1922\">Revolta do Forte de Copacabana</abbr> e a <abbr title=\"revolução de 1924 em São Paulo\">revolta paulista de 1924</abbr>. A <abbr title=\"marcha dos rebeldes pelo interior do Brasil\">Coluna Prestes</abbr>, comandada por <abbr title=\"militar comunista que liderou a coluna\">Luís Carlos Prestes</abbr>, percorreu o país pregando a reforma e a redemocratização, sem atingir o governo.",
      "## A quebra de 1929",
      "A <abbr title=\"crise econômica mundial de 1929\">Grande Depressão</abbr> afundou os preços do café. Sem compradores, <abbr title=\"sacas de café que não tinham mercado\">milhões de sacas ficaram sem mercado</abbr>, e o governo queimou parte da produção. As <abbr title=\"camadas empobrecidas pela crise\">oligarquias e as classes médias</abbr> culparam o esquema de café com leite pela crise.",
      "## A eleição de 1930",
      "Na sucessão de <abbr title=\"presidente Washington Luis, paulista\">Washington Luís</abbr>, o <abbr title=\"candidato governista de São Paulo\">governo apoiou Júlio Prestes</abbr>, rompendo a alternância com Minas. Em resposta, formou-se a <abbr title=\"aliança de oposição de 1930\">Aliança Liberal</abbr>, que lançou <abbr title=\"candidato derrotado nas eleições de 1930\">Getúlio Vargas</abbr> contra o governista. Com denúncias de fraude no pleito de março, os oposicionistas armaram-se: o <abbr title=\"assassinato de João Pessoa, vice de Vargas\">assassinato de João Pessoa\</abbr>, em julho, tornou-se o estopim.",
      "## A revolução vencedora",
      "Em outubro, a <abbr title=\"levante que derrubou Washington Luís\">Revolução de 1930</abbr> estourou: <abbr title=\"estados como Rio Grande do Sul e Minas Gerais aderiram\">vários estados aderiram</abbr>, e o presidente foi deposto em <abbr title=\"dia da queda de Washington Luís\">24 de outubro</abbr>. Vargas assumiu a chefia do <abbr title=\"governo provisório de 1930\">governo provisório</abbr>. A República Velha caiu; começava uma nova era — marcada pelo Estado forte, pela indústria e pelas transformações que viriam com a Era Vargas."
    ], vocabulario: [
      ["Coluna Prestes", "marcha militar rebelde pelo interior do Brasil"],
      ["Aliança Liberal", "oposição que lançou Vargas em 1930"],
      ["Revolução de 1930", "levante que derrubou a República Velha"],
      ["governo provisório", "governo de Vargas após a revolução"]
    ] },

    { num: "1.56", titulo: "A Era Vargas", paragrafos: [
      "De <abbr title=\"período de 1930 a 1945\">1930 a 1945</abbr>, o Brasil foi comandado por uma única figura: <abbr title=\"presidente que dominou a política brasileira por 15 anos\">Getúlio Vargas</abbr>. Foi a era do Estado forte, das leis trabalhistas e da industrialização acelerada.",
      "## O governo provisório e a Constituição de 1934",
      "Vargas centralizou o poder e nomeou <abbr title=\"governadores estaduais escolhidos por Vargas\">interventores</abbr> para os estados. A <abbr title=\"revolução constitucionalista de São Paulo em 1932\">Revolução Constitucionalista</abbr> exigiu uma Constituição; a nova <abbr title=\"constituição promulgada em 1934\">Carta de 1934</abbr> garantiu <abbr title=\"direitos como voto feminino e leis trabalhistas\">voto feminino e direitos trabalhistas</abbr>, mas Vargas tampouco se contentou com limites.",
      "## O Estado Novo",
      "Com o pretexto do <abbr title=\"ameaça comunista do levante de 1935\">levante comunista de 1935</abbr> (a <abbr title=\"intentona comunista de 1935\">Intentona de 1935</abbr>), Vargas virou ditador: em <abbr title=\"golpe de novembro de 1937\">10 de novembro de 1937</abbr>, decretou o <abbr title=\"ditadura do Estado Novo, com a polícia política\">Estado Novo</abbr>, fechou o Congresso, impôs uma <abbr title=\"constituição outorgada de 1937, a intrusa\">Constituição autoritária</abbr> (a \"<abbr title=\"apelido da carta de 1937\">Polaca</abbr>\") e criou o <abbr title=\"órgão de propaganda de Vargas, o DIP\">Departamento de Imprensa e Propaganda (DIP)</abbr> e a <abbr title=\"polícia política de Vargas\">polícia política</abbr> do <abbr title=\"delegacia de repressão política de Vargas\">DOPS</abbr>.",
      "## Trabalho e indústria",
      "Para os trabalhadores, o Estado Novo criou a <abbr title=\"conjunto de leis trabalhistas de Vargas\">Consolidação das Leis do Trabalho (CLT)</abbr> em <abbr title=\"ano da CLT, 1943\">1943</abbr>, com <abbr title=\"salário mínimo, férias e carteira\">salário mínimo, férias e carteira assinada</abbr>. O mesmo governo de <abbr title=\"propaganda que pintava Vargas como pai dos pobres\">pai dos pobres</abbr> manteve controle sobre os sindicatos. A <abbr title=\"estatal de siderurgia criada em 1941\">Companhia Siderúrgica Nacional</abbr> e a <abbr title=\"empresa de mineração criada em 1942\">Companhia Vale do Rio Doce</abbr> impulsionaram a indústria — era o <abbr title=\"política de desenvolvimento econômico estatal\">nacional-desenvolvimentismo</abbr>.",
      "## A guerra e a queda",
      "Na <abbr title=\"segunda guerra mundial de 1939 a 1945\">Segunda Guerra Mundial</abbr>, o Brasil acabou ao lado dos <abbr title=\"aliança contra o nazismo\">Aliados</abbr>, enviando a <abbr title=\"tropa brasileira que lutou na Itália\">Força Expedicionária Brasileira (FEB)</abbr>, e a população esperava o retorno da democracia. Em <abbr title=\"data da deposição de Vargas\">29 de outubro de 1945</abbr>, os militares o depuseram. Vargas saiu pela porta do fundo — mas voltaria, por voto, em 1950, num desfecho que ainda emociona o país."
    ], vocabulario: [
      ["Estado Novo", "ditadura de Vargas de 1937 a 1945"],
      ["CLT", "Consolidação das Leis do Trabalho"],
      ["nacional-desenvolvimentismo", "política de desenvolvimento com estatal"],
      ["FEB", "Força Expedicionária Brasileira"]
    ] },

    { num: "1.57", titulo: "A República Liberal Populista (1945-1964)", paragrafos: [
      "Depois de Vargas, o Brasil viveu quase 20 anos de democracia — ainda que instável, marcada por populismo, crises e golpes que se ensaiavam. De <abbr title=\"período de 1945 a 1964\">1945 a 1964</abbr>, presidiram a república presidentes eleitos e um interino, num equilíbrio que acabou rompido.",
      "## A redemocratização",
      "Com a <abbr title=\"queremismo, o movimento que queria manter Vargas\">pressão popular\</abbr> e a <abbr title=\"eleição de 1945, a primeira democrática\">eleição de dezembro de 1945</abbr>, o <abbr title=\"marechal que venceu as eleições de 1945\">Eurico Gaspar Dutra</abbr> assumiu. A <abbr title=\"constituição promulgada em 1946\">Constituição de 1946</abbr> restaurou as liberdades, e o <abbr title=\"partido comunista, cassado em 1947\">Partido Comunista</abbr> foi logo cassado no clima da <abbr title=\"conflito entre EUA e URSS\">Guerra Fria</abbr>.",
      "## O governo Vargas (1951-1954)",
      "Eleito, Vargas voltou com discurso <abbr title=\"estilo de governo que seduz as massas\">populista</abbr>. Criou a <abbr title=\"estatal de petróleo criada em 1953\">Petrobras</abbr> (1953), aumentou o <abbr title=\"salário mínimo que Vargas dobrou, irritando oposição\">salário mínimo em 100%</abbr> e enfrentou a abertura da <abbr title=\"imprensa que o atacava e o escândalo\">campanha contra ele</abbr>. Após o <abbr title=\"tentativa de assassinato de Carlos Lacerda\">atentado contra Carlos Lacerda\</abbr>, Vargas foi pressionado e, em <abbr title=\"data do suicídio de Vargas\">24 de agosto de 1954</abbr>, suicidou-se — deixando uma <abbr title=\"carta-testamento de Vargas\">carta-testamento</abbr> que ecoou no país.",
      "## De Juscelino a Jânio",
      "<abbr title=\"presidente que governou de 1956 a 1961\">Juscelino Kubitschek</abbr> cumpriu a promessa de \"<abbr title=\"slogan de JK, cinquenta anos em cinco\">50 anos em 5</abbr>\": acelerou a indústria automobilística e construiu <abbr title=\"nova capital federal inaugurada em 1960\">Brasília</abbr>. <abbr title=\"presidente Jânio Quadros, que governou 7 meses em 1961\">Jânio Quadros</abbr> renunciou em <abbr title=\"renúncia surpresa de Jânio em agosto de 1961\">agosto de 1961</abbr>, deixando o vice <abbr title=\"vice-presidente que assumiu a presidência\">João Goulart (Jango)</abbr>, um trabalhista, em meio a temores de golpe.",
      "## A queda de Jango e o golpe",
      "Para conter Jango, militares impuseram o <abbr title=\"tentativa de limitar os poderes de Jango em 1961\">parlamentarismo (1961-1963)</abbr>. Com plebiscito, Jango recuperou os poderes e pregou as <abbr title=\"reformas de base: agrária, tributária, urbana\">Reformas de Base</abbr>, que assustaram as elites. Em <abbr title=\"comício da Central do Brasil, em 13 de março de 1964\">março de 1964</abbr>, o comício pelas reformas agitou a oposição. Em <abbr title=\"data do golpe militar de 1964\">31 de março de 1964</abbr>, o exército marchou sobre o Rio, e o presidente caiu — <abbr title=\"golpe que instituiu a ditadura\">encerrando a república populista</abbr> e instalando a ditadura."
    ], vocabulario: [
      ["populismo", "governo que seduz as massas com carisma"],
      ["Petrobras", "estatal de petróleo criada em 1953"],
      ["Reformas de Base", "propostas de Jango de reformas sociais"],
      ["plebiscito de 1963", "consulta popular que devolveu poderes a Jango"]
    ] }
  ]}
]);